version: '3'
services:
  api:
#    init: true
#    restart: "on-failure:3"
    build:
      context: .
    image: w3b3/api_youtube_subscriptions:latest
    container_name: api
    hostname: api
    labels:
      - "ca.codein.api=API entrypoint"
      #    develop:
      #      watch:
      #        - path: ./src
      #          action: sync+restart
      #    depends_on:
      #      - db
    expose:
      - "1235"
    ports:
      - "1235:1235"
    env_file:
      - ./a.env
        #      - ./b.env
        #    environment:
      #  - PORT=1233
    # entrypoint?
    # https://docs.docker.com/compose/compose-file/develop/
    #    command: ["echo", "Foo: ${FOO}"]
    #   cpu_count: 1
    #    cpu_percent: 50
    #    configs:
    #      - nginx
    # https://docs.docker.com/compose/compose-file/05-services/#network_mode
    networks:
      - youtube_api
    volumes:
      #      - api:/app
      - type: bind
        source: ./src
        target: /app

        #  db:
        #    image: postgres
        #    environment:
        #      POSTGRES_DB:  ioiewoiru923
        #      POSTGRES_USER: x123lkjasd23
        #      POSTGRES_PASSWORD: $#%DsdfSDF@#$%
        #    volumes:
        #      - db-data:/bar
# TODO: FUTURE IMPROVEMENT
# https://docs.docker.com/compose/compose-file/05-services/#healthcheck
# https://docs.docker.com/compose/compose-file/06-networks/
networks:
  youtube_api:
    #volumes:
    #  api:
#configs:
#  nginx:
#    file: ./nginx.conf
